"""create_users_loans_payments_tables

Revision ID: 2d87fd2934f4
Revises: 
Create Date: 2026-10-04 14:55:40.680004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d87fd2934f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'BORROWER', name='user_role', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),

    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('loan_date', sa.Date(), nullable=False),
    sa.Column('total_payable', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('minimum_monthly_payment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DEFAULTED', name='loan_status', create_constraint=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),

    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_borrower_id'), 'loans', ['borrower_id'], unique=False)
    op.create_index('ix_loans_loan_date', 'loans', ['loan_date'], unique=False)
    op.create_index('ix_loans_status', 'loans', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_month', sa.String(length=7), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='payment_status', create_constraint=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),

    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_borrower_id'), 'payments', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_payments_loan_id'), 'payments', ['loan_id'], unique=False)
    op.create_index('ix_payments_payment_month', 'payments', ['payment_month'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_payment_month', table_name='payments')
    op.drop_index(op.f('ix_payments_loan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_borrower_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_loans_status', table_name='loans')
    op.drop_index('ix_loans_loan_date', table_name='loans')
    op.drop_index(op.f('ix_loans_borrower_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
